name: Get Go versions
on:
  workflow_dispatch:

jobs:
  get-new-go-versions:
    uses: actions/versions-package-tools/.github/workflows/get-new-tool-versions.yml@main
    with:
      tool-name: "Go"
      image-url: "https://go.dev/images/gopher-footer.jpg"
    secrets: inherit
